 # # # # # # # # # # # # # # # # # #
 # Henrique Noronha Facioli        #
 # RA : 157986                     #
 # henrique.facioli@gmail.com      #
 # henrique.facioli@ic.unicamp.br  #
 # github : henriquefacioli        #
 # Makefile                        #
 # # # # # # # # # # # # # # # # # #


# Compila todos os arquivos .c
all:
	gcc -std=c99 src/*.c -o ias-as

clean:
	rm -r ias-as
